"""empty message

Revision ID: 06aee275bb65
Revises: f7ef19325ffc
Create Date: 2021-02-15 16:53:12.404834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06aee275bb65'
down_revision = 'f7ef19325ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_code', sa.String(), nullable=True),
    sa.Column('dg_code', sa.Integer(), nullable=True),
    sa.Column('full_code', sa.String(), nullable=True),
    sa.Column('abb_des', sa.String(), nullable=True),
    sa.Column('full_des', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('diagnosis_codes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cat_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dg_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('abb_des', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_des', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='diagnosis_codes_pkey')
    )
    op.drop_table('diagnosis')
    # ### end Alembic commands ###
