"""empty message

Revision ID: b6fb8cd02eca
Revises: b7c295ba17b7
Create Date: 2021-02-15 16:49:48.206776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fb8cd02eca'
down_revision = 'b7c295ba17b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_code', sa.String(), nullable=True),
    sa.Column('dg_code', sa.Integer(), nullable=True),
    sa.Column('full_code', sa.String(), nullable=True),
    sa.Column('abb_des', sa.String(), nullable=True),
    sa.Column('full_des', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnosis')
    # ### end Alembic commands ###
