"""empty message

Revision ID: b7c295ba17b7
Revises: 6c25f6b2dcc8
Create Date: 2021-02-14 12:31:44.405767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c295ba17b7'
down_revision = '6c25f6b2dcc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_code', sa.String(), nullable=True),
    sa.Column('dg_code', sa.Integer(), nullable=True),
    sa.Column('full_code', sa.String(), nullable=True),
    sa.Column('abb_des', sa.String(), nullable=True),
    sa.Column('full_des', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cars_pkey')
    )
    op.drop_table('diagnosis_codes')
    # ### end Alembic commands ###
